steps:
    # Install
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    # Build
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
    # Deploy
    - name: 'gcr.io/host-test-4cd54/firebase'
      args: ['target:apply hosting develop-bc122 deploy hosting:develop-bc122']
