steps:
    # Install
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    # Build
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
    # Deploy
    - name: 'gcr.io/host-test-4cd54/firebase'
      args: ['firebase deploy --project host-test-4cd54']