steps:
    # Install
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    # Build
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
    # Deploy-develop
    - name: 'gcr.io/host-test-4cd54/firebase'
      only: 'develop'
      args: ['deploy', '--only=hosting:develop']
    # Deploy-production
    - name: 'gcr.io/host-test-4cd54/firebase'
      only: 'production'
      args: ['deploy', '--only=hosting:production']
